create materialized view "SeriesCatalogView" as 
with timeunits as ( select * from "Units"),
     series as (select "Sites"."SiteID","Sites"."SiteCode","Sites"."SiteName","Sites"."SiteType","Variables"."VariableID","Variables"."VariableCode","Variables"."VariableName","Variables"."Speciation","Variables"."VariableUnitsID","Units"."UnitsName" "VariableUnitsName","Variables"."SampleMedium","Variables"."ValueType","Variables"."TimeSupport","Variables"."TimeUnitsID",timeunits."UnitsName" "TimeUnitsName","Variables"."DataType","Variables"."GeneralCategory","Methods"."MethodID","Methods"."MethodDescription","Sources"."SourceID","Sources"."Organization","Sources"."SourceDescription","Sources"."Citation","QualityControlLevels"."QualityControlLevelID","QualityControlLevels"."QualityControlLevelCode",min("DataValues"."LocalDateTime") "BeginDateTime",max("DataValues"."LocalDateTime") "EndDateTime", min("DataValues"."DateTimeUTC") "BeginDateTimeUTC", max("DataValues"."DateTimeUTC") "EndDateTimeUTC",count("DataValues"."DataValue") "ValueCount" from "Sites","Variables","Sources","DataValues","QualityControlLevels","Methods","Units",timeunits where "Sites"."SiteID"="DataValues"."SiteID" and "Variables"."VariableID"="DataValues"."VariableID" and "Sources"."SourceID"="DataValues"."SourceID" and "QualityControlLevels"."QualityControlLevelID"="DataValues"."QualityControlLevelID" and "Methods"."MethodID"="DataValues"."MethodID" and "Units"."UnitsID"="Variables"."VariableUnitsID" and timeunits."UnitsID"="Variables"."TimeUnitsID"  group by "Sites"."SiteID","Sites"."SiteCode","Sites"."SiteName","Sites"."SiteType","Variables"."VariableID","Variables"."VariableCode","Variables"."VariableName","Variables"."Speciation","Variables"."VariableUnitsID","Units"."UnitsName","Variables"."SampleMedium","Variables"."ValueType","Variables"."TimeSupport","Variables"."TimeUnitsID",timeunits."UnitsName","Variables"."DataType","Variables"."GeneralCategory","Methods"."MethodID","Methods"."MethodDescription","Sources"."SourceID","Sources"."Organization","Sources"."SourceDescription","Sources"."Citation","QualityControlLevels"."QualityControlLevelID","QualityControlLevels"."QualityControlLevelCode" order by "Sites"."SiteID","Sites"."SiteCode","Sites"."SiteName","Sites"."SiteType","Variables"."VariableID","Variables"."VariableCode","Variables"."VariableName","Variables"."Speciation","Variables"."VariableUnitsID","Units"."UnitsName","Variables"."SampleMedium","Variables"."ValueType","Variables"."TimeSupport","Variables"."TimeUnitsID",timeunits."UnitsName","Variables"."DataType","Variables"."GeneralCategory","Methods"."MethodID","Methods"."MethodDescription","Sources"."SourceID","Sources"."Organization","Sources"."SourceDescription","Sources"."Citation","QualityControlLevels"."QualityControlLevelID","QualityControlLevels"."QualityControlLevelCode")
select row_number() over (order by "SiteID","VariableID","SourceID") as "SeriesID",* from series;

grant select on "SeriesCatalogView" to sololectura;
grant select on "SeriesCatalogView" to actualiza;

select cron.schedule('0 */3 * * *',$$refresh materialized view "SeriesCatalogView"$$);
