--
-- PostgreSQL database dump
--

-- Dumped from database version 9.5.13
-- Dumped by pg_dump version 9.5.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: ValueTypeCV; Type: TABLE DATA; Schema: public; Owner: jbianchi
--

COPY public."ValueTypeCV" ("Term", "Definition") FROM stdin;
Calibration Value	A value used as part of the calibration of an instrument at a particular time.
Derived Value	Value that is directly derived from an observation or set of observations
Field Observation	Observation of a variable using a field instrument
Model Simulation Result	Values generated by a simulation model
Sample	Observation that is the result of analyzing a sample in a laboratory
Unknown	The value type is unknown
\.


--
-- PostgreSQL database dump complete
--

